development:
  adapter: postgresql
  database: training1_dev
  host: localhost
  min_messages: warning
  username:

test:
  adapter: postgresql
  database: training1_test
  host: localhost
  min_messages: warning
  username: